// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "backend": string;
      "codexPath": string;
      "model": string;
      "reasoningEffort": string;
      "claudePath": string;
      "claudeModel": string;
      "permissionMode": string;
      "webSearch": boolean;
      "timeoutSec": number;
    };
  }
}
